### ISSUE TITLE
Browser:GetMainFrame() returns userdata with no metatable

### ISSUE THREAD

**Issue by stof-soft** [wy3/luacef#3]
Hi  ,
I Implimented  luacef in my project
But when I try to get Frame via 
browser:GetMainFrame()
or 
browser:Frame(0)
browser:Frame(1)
browser:Frame(2)
or 
browser:GetFocusedFrame()

it  returns userdata without any methods 

details : 
local frame = browser:GetMainFrame()
frame:GetURL() --> attempt to index a userdata value (local 'frame')

for k , v in pairs( getmettable( frame  ) )  print(k) end 
-->bad argument #1 to 'for iterator' (table expected, got nil)

Thanks in advance for this great project;

**Comment by nomi-san** [comment]
To use `CefFrame`, please add `luacef_Frame_reg` in `luaopen_luacef` function:
```diff
// luacef.c
EXPORT(int) luaopen_luacef(lua_State* L) {
...
    luacef_handler_reg(L);
    luacef_types_reg(L);
    luacef_funcs_reg(L);
+   luacef_Frame_reg(L);
...
}
```
---
Btw, this project is unstable, I just write for fun.
The **reborn** branch is new implementation, written in C++. I'll continue it soon.
