### ISSUE TITLE
error: The specified procedure could not be found.

### ISSUE THREAD

**Issue by exect3r** [wy3/luacef#4]
**Platform**: Windows 10 x64
**GCC**: version 7.3.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)
**Lua**: 5.3 x64

The project builds successfully (after changing 'luacef_frame_reg' to 'luacef_Frame_reg' on line 316),
but running the lua code in readme hangs at the first line with error:
```
C:\lua\lua53.exe: error loading module 'luacef' from file '.\luacef.dll':
        The specified procedure could not be found.

stack traceback:
        [C]: in ?
        [C]: in function 'require'
        .\test.lua:1: in main chunk
        [C]: in ?
```
Both the lua code and 'luacef.dll' are in the 'Release' folder of 'cef-minimal'.

**Comment by nomi-san** [comment]
This error means, the function `luaopen_luacef` is not visible (exported) in DLL.
- Please check the definition of `EXPORT`.
https://github.com/nomi-san/luacef/blob/ed296e8793cf394ff85c1eef92835e92f7b96f1e/src/luacef.h#L15-L18
https://github.com/nomi-san/luacef/blob/ed296e8793cf394ff85c1eef92835e92f7b96f1e/src/luacef.c#L307-L311
- Please make sure **CEF** binaries, **luacef** and **Lua** are same arch (x64 in this case).

**Comment by exect3r** [comment]
I got it working.
For some reason `__attribute__((visibility("default")))` does not seem to expose the function correctly. I changed it to `__declspec(dllexport)` and it works fine.
